/**
 * @module batch-api-demo
 * @description Demonstrates Anthropic Batch API patterns and constraints.
 *
 * @exam Domain 4.5 — Batch Processing
 *
 * EXAM NOTE: The Batch API does NOT support multi-turn tool calling.
 * If a response contains a tool_use block, the batch cannot automatically
 * execute the tool and continue the conversation. Use Batch API only for
 * single-turn requests (with or without single-turn tool use where you
 * handle the tool_use response yourself after the batch completes).
 *
 * EXAM NOTE: Results are NOT guaranteed to be returned in input order.
 * Use custom_id to correlate requests with responses. The custom_id you
 * provide in each request appears verbatim in the corresponding result.
 *
 * EXAM NOTE: Batch API offers a 50% cost reduction compared to standard
 * Messages API calls, but has a processing window of up to 24 hours.
 * Use it for non-latency-sensitive workloads.
 *
 * This file is a reference implementation — it demonstrates the patterns
 * and constraints students need to know for the exam. It is NOT executed
 * at runtime.
 *
 * @author Yuki Tanaka, Prompt Engineer — ArchitectAI
 */

import type Anthropic from "@anthropic-ai/sdk";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * A single request in a batch.
 *
 * EXAM NOTE: `custom_id` is YOUR unique identifier for correlating requests
 * with responses. It is not generated by the API — you must provide it.
 * It appears unchanged in the response, so use a meaningful value
 * (e.g., a question ID, row number, or UUID).
 */
interface BatchRequest {
  custom_id: string;
  params: Anthropic.Messages.MessageCreateParams;
}

/**
 * A single result from a completed batch.
 *
 * EXAM NOTE: The `custom_id` in the result matches exactly what you sent.
 * Results may arrive in any order — always look up by custom_id, never
 * assume positional correspondence with the input array.
 */
interface BatchResult {
  custom_id: string;
  result: {
    type: "succeeded" | "errored" | "expired";
    message?: Anthropic.Messages.Message;
    error?: { type: string; message: string };
  };
}

// ---------------------------------------------------------------------------
// Batch request construction
// ---------------------------------------------------------------------------

/**
 * Create batch requests for quality-reviewing exam questions.
 *
 * @exam Domain 4.5 — Batch request construction with custom_id correlation.
 *
 * @param questions - Array of questions to review.
 * @returns Array of BatchRequest objects ready for submission.
 *
 * @example
 * ```ts
 * const requests = createBatchRequests([
 *   { id: "d1-q01", text: "What is the primary stop signal for an agentic loop?" },
 *   { id: "d2-q03", text: "Which tool_choice mode forces a specific tool?" },
 * ]);
 * // requests[0].custom_id === "d1-q01"
 * // requests[1].custom_id === "d2-q03"
 * ```
 */
function createBatchRequests(
  questions: Array<{ id: string; text: string }>,
): BatchRequest[] {
  return questions.map((q) => ({
    custom_id: q.id,
    params: {
      model: "claude-sonnet-4-20250514",
      max_tokens: 1024,
      messages: [
        {
          role: "user" as const,
          content: `Review this CCA-F exam question for quality. Check for:\n` +
            `1. Clear, unambiguous scenario\n` +
            `2. Exactly one correct answer\n` +
            `3. Plausible distractors (wrong answers that test real misconceptions)\n` +
            `4. Accurate exam domain/task mapping\n\n` +
            `Question: ${q.text}`,
        },
      ],
    },
  }));
}

// ---------------------------------------------------------------------------
// Batch result processing
// ---------------------------------------------------------------------------

/**
 * Process batch results, correlating by custom_id.
 *
 * EXAM NOTE: We iterate results and look up by custom_id — we do NOT
 * assume results are in the same order as the input requests. This is
 * a critical exam concept: batch results are unordered.
 *
 * @param results - Raw results from the batch API.
 * @returns A Map of custom_id → review text (for succeeded) or error message.
 */
function processBatchResults(
  results: BatchResult[],
): Map<string, { success: boolean; content: string }> {
  const processed = new Map<string, { success: boolean; content: string }>();

  for (const result of results) {
    if (result.result.type === "succeeded" && result.result.message) {
      const textBlocks = result.result.message.content.filter(
        (block): block is Anthropic.Messages.TextBlock => block.type === "text",
      );
      const text = textBlocks.map((b) => b.text).join("\n");

      processed.set(result.custom_id, { success: true, content: text });
    } else if (result.result.type === "errored") {
      processed.set(result.custom_id, {
        success: false,
        content: `Error: ${result.result.error?.message ?? "Unknown error"}`,
      });
    } else {
      // "expired" — the request was not processed within the batch window
      processed.set(result.custom_id, {
        success: false,
        content: "Request expired — not processed within the 24-hour batch window.",
      });
    }
  }

  return processed;
}

// ---------------------------------------------------------------------------
// Exam anti-patterns (documented for study purposes)
// ---------------------------------------------------------------------------

/**
 * EXAM ANTI-PATTERN: Trying to use Batch API for multi-turn conversations.
 *
 * The Batch API processes each request as a SINGLE API call. If the model
 * responds with stop_reason === "tool_use", the batch does NOT execute the
 * tool and continue. The conversation stops at that single turn.
 *
 * If you need multi-turn tool use, use the standard Messages API with an
 * agentic loop (see src/agents/loop.ts).
 *
 * EXAM ANTI-PATTERN: Assuming results are ordered.
 * Always correlate by custom_id. Never use array index.
 */

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export { createBatchRequests, processBatchResults };
export type { BatchRequest, BatchResult };
